pull_request_rules:
  - name: Automatic approve on dependabot PR
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - check-success=Build
    actions:
      review:
        type: APPROVE
  - name: Automatic merge on dependabot PR after success CI
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - check-success=Build
    actions:
      merge:
        method: rebase
        strict: smart
